import rules from './index.cjs';

export const getCantripsKnownLimit = rules.getCantripsKnownLimit;
export const getKnownSpellsLimit = rules.getKnownSpellsLimit;
export const getSrdClassDefinition = rules.getSrdClassDefinition;
export const getSrdClassSpellcastingProgression = rules.getSrdClassSpellcastingProgression;
export const normalizeSrdCharacterClassKey = rules.normalizeSrdCharacterClassKey;
export const normalizeSrdCharacterLevel = rules.normalizeSrdCharacterLevel;
export const resolveAbilityModifier = rules.resolveAbilityModifier;
export const resolveAbilityScoreImprovementLevels = rules.resolveAbilityScoreImprovementLevels;
export const resolveAvailableAbilityScoreImprovementLevels = rules.resolveAvailableAbilityScoreImprovementLevels;
export const resolveCharacterSpellSelectionRequirements = rules.resolveCharacterSpellSelectionRequirements;
export const resolveCrossedAbilityScoreImprovementLevels = rules.resolveCrossedAbilityScoreImprovementLevels;
export const resolveKnownSpellDelta = rules.resolveKnownSpellDelta;
export const resolveMaximumCastableSpellLevel = rules.resolveMaximumCastableSpellLevel;
export const resolvePreparedSpellAbility = rules.resolvePreparedSpellAbility;
export const resolvePreparedSpellLimit = rules.resolvePreparedSpellLimit;
export const resolveSpellcastingAbility = rules.resolveSpellcastingAbility;
export const resolveSpellSlotLimit = rules.resolveSpellSlotLimit;
export const resolveSubclassChoiceLevel = rules.resolveSubclassChoiceLevel;
export const resolveWizardSpellbookSpellCount = rules.resolveWizardSpellbookSpellCount;
export const usesDynamicPreparedSpellPool = rules.usesDynamicPreparedSpellPool;
