export const MONSTER_ACTION_UNAVAILABLE_REASONS = {
  RECHARGE_EXPENDED: "MONSTER_RECHARGE_ACTION_EXPENDED",
  LIMITED_USE_EXPENDED: "MONSTER_LIMITED_USE_ACTION_EXPENDED",
} as const;

export type MonsterActionUnavailableReason =
  (typeof MONSTER_ACTION_UNAVAILABLE_REASONS)[keyof typeof MONSTER_ACTION_UNAVAILABLE_REASONS];

