export const CHAT_MESSAGE_MAX_LENGTH = 1000;

export const HUMAN_GM_MESSAGE_CONTENT_MAX_LENGTH = 2000;

export const HUMAN_GM_PRIVATE_NOTE_MAX_LENGTH = 1000;

export const HUMAN_GM_AI_ASSIST_CONTENT_MAX_LENGTH = 2000;

export const HUMAN_GM_AI_ASSIST_PROMPT_MAX_LENGTH = 500;

export const MAIN_COMMAND_PENDING_LOG_TIMEOUT_MS = 45_000;

export const HUMAN_GM_INVENTORY_QUANTITY_MIN = 1;

export const HUMAN_GM_INVENTORY_QUANTITY_MAX = 99;

export const VTT_ENCOUNTER_PRIORITY_MIN = 0;

export const VTT_ENCOUNTER_PRIORITY_MAX = 99;

export const VTT_CHECK_DC_MIN = 1;

export const VTT_CHECK_DC_MAX = 40;
