export const MAIN_COMMAND_CONFIDENCE = {
  HOSTILE_PERSUASION_REJECT_THRESHOLD: 0.65,
  INTIMIDATE_MINIMUM: 0.45,
  FRIENDLY_INTIMIDATION_REJECT_THRESHOLD: 0.7,
  DECEPTION_MINIMUM: 0.45,
  TOOL_OR_OBJECT_GM_REVIEW_THRESHOLD: 0.6,
  DEFAULT_GM_REVIEW_THRESHOLD: 0.55,
  ROUTER_ROUTE_FLOOR: 0.55,
} as const;

export const TRANSITION_MATCH_POLICY = {
  PARTIAL_MATCH_RATIO: 0.7,
  EXACT_MATCH_TERM_LIMIT: 3,
} as const;

