import {
  RuleCatalogEntry,
  RuleCost,
  RuleTargeting,
} from "./rule-catalog.types";

type P4MonsterSeed = {
  monsterId: string;
  abilityId: string;
  cost?: RuleCost;
  targeting?: RuleTargeting;
  save?: RuleCatalogEntry["save"];
  damage?: RuleCatalogEntry["damage"];
  tags: string[];
  hookId?: string;
};

const ACTION: RuleCost = { type: "action" };
const NONE: RuleCost = { type: "none" };
const SELF: RuleTargeting = { type: "self" };

export const P4_EXECUTABLE_MONSTER_IDS = [
  "monster.air_elemental",
  "monster.earth_elemental",
  "monster.fire_elemental",
  "monster.invisible_stalker",
  "monster.salamander",
  "monster.xorn",
  "monster.ankheg",
  "monster.bulette",
  "monster.chimera",
  "monster.ettin",
  "monster.cyclops",
  "monster.frost_giant",
  "monster.fire_giant",
  "monster.stone_giant",
  "monster.young_black_dragon",
  "monster.young_green_dragon",
  "monster.young_white_dragon",
  "monster.young_brass_dragon",
  "monster.vampire_spawn",
  "monster.vampire",
  "monster.lich",
  "monster.medusa",
  "monster.minotaur",
  "monster.werewolf",
  "monster.wererat",
  "monster.werebear",
  "monster.giant_crocodile",
  "monster.giant_shark",
  "monster.giant_octopus",
  "monster.reef_shark",
  "monster.plesiosaurus",
  "monster.triceratops",
  "monster.tyrannosaurus_rex",
  "monster.nightmare",
  "monster.phase_spider",
  "monster.roper",
  "monster.purple_worm",
  "monster.remorhaz",
  "monster.hydra",
  "monster.cloaker",
  "monster.assassin",
  "monster.berserker",
  "monster.knight",
  "monster.veteran",
  "monster.gladiator",
  "monster.bandit_captain",
  "monster.archmage",
  "monster.scout",
  "monster.spy",
  "monster.thug",
] as const;

function ability(seed: P4MonsterSeed): RuleCatalogEntry {
  return {
    id: `${seed.monsterId}.ability.${seed.abilityId}`,
    kind: "monster_abilities",
    source: "SRD5E",
    levelRequirement: { monsterId: seed.monsterId },
    trigger:
      seed.cost?.type === "bonus_action"
        ? "bonus_action"
        : seed.cost?.type === "reaction"
          ? "reaction"
          : seed.cost?.type === "none"
            ? "always"
            : "action",
    cost: seed.cost ?? ACTION,
    targeting: seed.targeting ?? { type: "creature", rangeFt: 5 },
    save: seed.save ?? null,
    damage: seed.damage ?? null,
    duration: null,
    concentration: false,
    scaling: null,
    runtimeEffect: {
      type: "monster_ability",
      tags: ["p4_content", ...seed.tags],
      hookId: seed.hookId ?? "hook.monster.attack",
    },
  };
}

const P4_MONSTER_SEEDS: P4MonsterSeed[] = [
  {
    monsterId: "monster.air_elemental",
    abilityId: "whirlwind",
    targeting: { type: "area", shape: "sphere", sizeFt: 10 },
    save: { ability: "str", dcSource: "fixed", fixedDc: 13 },
    damage: { dice: "3d8+2", type: "bludgeoning" },
    tags: ["role:mobile", "movement:fly:90", "condition:prone", "recharge:4-6"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.earth_elemental",
    abilityId: "slam",
    damage: { dice: "2d8+5", type: "bludgeoning" },
    tags: ["role:brute", "attack:melee_weapon", "attack_bonus:+8", "srd_action_id:action.slam", "burrow:30"],
  },
  {
    monsterId: "monster.fire_elemental",
    abilityId: "touch",
    damage: { dice: "2d6+3", type: "fire" },
    tags: ["role:mobile", "attack:melee_weapon", "attack_bonus:+6", "condition:burning", "aura:fire_form"],
  },
  {
    monsterId: "monster.invisible_stalker",
    abilityId: "slam",
    damage: { dice: "2d6+3", type: "bludgeoning" },
    tags: ["role:skirmisher", "condition:invisible", "attack:melee_weapon", "attack_bonus:+6", "tracking:faultless"],
  },
  {
    monsterId: "monster.salamander",
    abilityId: "heated_spear",
    damage: { dice: "2d6+4+1d6", type: "piercing_fire" },
    tags: ["role:soldier", "attack:melee_weapon", "attack_bonus:+7", "reach:10", "heated_body"],
  },
  {
    monsterId: "monster.xorn",
    abilityId: "claws_and_bite",
    damage: { dice: "3d6+3", type: "slashing_piercing" },
    tags: ["role:brute", "multiattack:claw_bite", "earth_glide", "treasure_sense"],
  },
  {
    monsterId: "monster.ankheg",
    abilityId: "acid_spray",
    targeting: { type: "area", shape: "line", sizeFt: 30 },
    save: { ability: "dex", dcSource: "fixed", fixedDc: 13 },
    damage: { dice: "3d6", type: "acid" },
    tags: ["role:ambusher", "save:dex", "half_damage_on_success", "recharge:6"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.bulette",
    abilityId: "deadly_leap",
    targeting: { type: "area", shape: "sphere", sizeFt: 15 },
    save: { ability: "str", dcSource: "fixed", fixedDc: 16 },
    damage: { dice: "3d6+4", type: "bludgeoning" },
    tags: ["role:brute", "movement:burrow:40", "condition:prone", "jump_attack"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.chimera",
    abilityId: "fire_breath",
    targeting: { type: "area", shape: "cone", sizeFt: 15 },
    save: { ability: "dex", dcSource: "fixed", fixedDc: 15 },
    damage: { dice: "7d8", type: "fire" },
    tags: ["role:boss", "movement:fly:60", "multiattack:bite_horns_claws", "recharge:5-6"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.ettin",
    abilityId: "two_heads_multiattack",
    damage: { dice: "2d8+5", type: "bludgeoning_slashing" },
    tags: ["role:brute", "multiattack:battleaxe_morningstar", "advantage:perception", "advantage:save:charmed_frightened_stunned_unconscious"],
    hookId: "hook.monster.multiattack",
  },
  {
    monsterId: "monster.cyclops",
    abilityId: "rock",
    targeting: { type: "creature", rangeFt: 30 },
    damage: { dice: "4d10+6", type: "bludgeoning" },
    tags: ["role:artillery", "attack:ranged_weapon", "attack_bonus:+9", "range_long:120"],
  },
  {
    monsterId: "monster.frost_giant",
    abilityId: "greataxe",
    damage: { dice: "3d12+6", type: "slashing" },
    tags: ["role:soldier", "attack:melee_weapon", "attack_bonus:+9", "multiattack:greataxe:2", "immunity:cold"],
  },
  {
    monsterId: "monster.fire_giant",
    abilityId: "greatsword",
    damage: { dice: "6d6+7", type: "slashing" },
    tags: ["role:soldier", "attack:melee_weapon", "attack_bonus:+11", "multiattack:greatsword:2", "immunity:fire"],
  },
  {
    monsterId: "monster.stone_giant",
    abilityId: "rock",
    targeting: { type: "creature", rangeFt: 60 },
    damage: { dice: "4d10+6", type: "bludgeoning" },
    tags: ["role:artillery", "attack:ranged_weapon", "attack_bonus:+9", "range_long:240", "reaction:rock_catching"],
  },
  {
    monsterId: "monster.young_black_dragon",
    abilityId: "acid_breath",
    targeting: { type: "area", shape: "line", sizeFt: 30 },
    save: { ability: "dex", dcSource: "fixed", fixedDc: 14 },
    damage: { dice: "11d8", type: "acid" },
    tags: ["role:boss", "movement:fly:80", "movement:swim:40", "legendary_like:dragon", "recharge:5-6"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.young_green_dragon",
    abilityId: "poison_breath",
    targeting: { type: "area", shape: "cone", sizeFt: 30 },
    save: { ability: "con", dcSource: "fixed", fixedDc: 14 },
    damage: { dice: "12d6", type: "poison" },
    tags: ["role:boss", "movement:fly:80", "movement:swim:40", "recharge:5-6"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.young_white_dragon",
    abilityId: "cold_breath",
    targeting: { type: "area", shape: "cone", sizeFt: 30 },
    save: { ability: "con", dcSource: "fixed", fixedDc: 15 },
    damage: { dice: "10d8", type: "cold" },
    tags: ["role:boss", "movement:fly:80", "movement:burrow:30", "recharge:5-6"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.young_brass_dragon",
    abilityId: "sleep_breath",
    targeting: { type: "area", shape: "cone", sizeFt: 30 },
    save: { ability: "con", dcSource: "fixed", fixedDc: 14 },
    tags: ["role:controller", "movement:fly:80", "condition:unconscious", "recharge:5-6"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.vampire_spawn",
    abilityId: "bite",
    damage: { dice: "1d6+3+2d6", type: "piercing_necrotic" },
    tags: ["role:undead", "attack:melee_weapon", "attack_bonus:+6", "grapple_required", "max_hp_reduction"],
  },
  {
    monsterId: "monster.vampire",
    abilityId: "charm",
    targeting: { type: "creature", rangeFt: 30 },
    save: { ability: "wis", dcSource: "fixed", fixedDc: 17 },
    tags: ["role:boss", "condition:charmed", "legendary_like:movement", "shapechanger"],
    hookId: "hook.monster.save_condition",
  },
  {
    monsterId: "monster.lich",
    abilityId: "paralyzing_touch",
    damage: { dice: "3d6", type: "cold" },
    save: { ability: "con", dcSource: "fixed", fixedDc: 18 },
    tags: ["role:boss", "spellcaster:high", "condition:paralyzed", "legendary_resistance:3/day"],
  },
  {
    monsterId: "monster.medusa",
    abilityId: "petrifying_gaze",
    targeting: { type: "creature", rangeFt: 30 },
    save: { ability: "con", dcSource: "fixed", fixedDc: 14 },
    tags: ["role:controller", "condition:petrified", "save_sequence:two_failures", "avert_eyes"],
    hookId: "hook.monster.save_condition",
  },
  {
    monsterId: "monster.minotaur",
    abilityId: "gore",
    damage: { dice: "2d8+4", type: "piercing" },
    tags: ["role:brute", "attack:melee_weapon", "attack_bonus:+6", "charge:extra_damage", "condition:prone"],
  },
  {
    monsterId: "monster.werewolf",
    abilityId: "bite",
    damage: { dice: "1d8+2", type: "piercing" },
    tags: ["role:shapeshifter", "attack:melee_weapon", "attack_bonus:+4", "curse:lycanthropy", "immunity:nonmagical_non_silvered"],
  },
  {
    monsterId: "monster.wererat",
    abilityId: "hand_crossbow",
    targeting: { type: "creature", rangeFt: 30 },
    damage: { dice: "1d6+2", type: "piercing" },
    tags: ["role:skirmisher", "attack:ranged_weapon", "attack_bonus:+4", "range_long:120", "immunity:nonmagical_non_silvered"],
  },
  {
    monsterId: "monster.werebear",
    abilityId: "multiattack",
    damage: { dice: "2d10+4", type: "slashing_piercing" },
    tags: ["role:brute", "multiattack:bite_claws", "curse:lycanthropy", "immunity:nonmagical_non_silvered"],
    hookId: "hook.monster.multiattack",
  },
  {
    monsterId: "monster.giant_crocodile",
    abilityId: "bite",
    damage: { dice: "3d10+5", type: "piercing" },
    tags: ["role:aquatic", "movement:swim:50", "condition:grappled", "restrained:while_grappled"],
  },
  {
    monsterId: "monster.giant_shark",
    abilityId: "bite",
    damage: { dice: "3d10+6", type: "piercing" },
    tags: ["role:aquatic", "movement:swim:50", "blood_frenzy", "water_breathing"],
  },
  {
    monsterId: "monster.giant_octopus",
    abilityId: "tentacles",
    damage: { dice: "2d6+3", type: "bludgeoning" },
    tags: ["role:aquatic", "movement:swim:60", "condition:grappled", "restrained", "ink_cloud"],
  },
  {
    monsterId: "monster.reef_shark",
    abilityId: "bite",
    damage: { dice: "1d8+2", type: "piercing" },
    tags: ["role:aquatic_minion", "movement:swim:40", "pack_tactics", "water_breathing"],
  },
  {
    monsterId: "monster.plesiosaurus",
    abilityId: "bite",
    damage: { dice: "3d6+4", type: "piercing" },
    tags: ["role:aquatic", "movement:swim:40", "reach:10", "hold_breath"],
  },
  {
    monsterId: "monster.triceratops",
    abilityId: "trampling_charge",
    damage: { dice: "4d8+6", type: "piercing_bludgeoning" },
    save: { ability: "str", dcSource: "fixed", fixedDc: 13 },
    tags: ["role:brute", "condition:prone", "bonus_action:stomp", "charge"],
  },
  {
    monsterId: "monster.tyrannosaurus_rex",
    abilityId: "bite",
    damage: { dice: "4d12+7", type: "piercing" },
    tags: ["role:boss_brute", "condition:grappled", "restrained", "multiattack:bite_tail"],
  },
  {
    monsterId: "monster.nightmare",
    abilityId: "ethereal_stride",
    targeting: SELF,
    tags: ["role:fiend_mount", "movement:fly:90", "teleport:ethereal_plane", "fire_hooves"],
    hookId: "hook.monster.utility",
  },
  {
    monsterId: "monster.phase_spider",
    abilityId: "ethereal_jaunt",
    targeting: SELF,
    tags: ["role:ambusher", "movement:climb:30", "teleport:ethereal_phase", "poison_bite"],
    hookId: "hook.monster.utility",
  },
  {
    monsterId: "monster.roper",
    abilityId: "tendril",
    targeting: { type: "creature", rangeFt: 50 },
    save: { ability: "str", dcSource: "fixed", fixedDc: 15 },
    tags: ["role:controller", "condition:grappled", "condition:restrained", "pull:25ft", "false_appearance"],
    hookId: "hook.monster.save_condition",
  },
  {
    monsterId: "monster.purple_worm",
    abilityId: "swallow",
    damage: { dice: "3d8+9+6d6", type: "piercing_poison" },
    tags: ["role:boss_brute", "condition:swallowed", "burrow:30", "multiattack:bite_stinger"],
  },
  {
    monsterId: "monster.remorhaz",
    abilityId: "heated_bite",
    damage: { dice: "6d10+7+3d6", type: "piercing_fire" },
    tags: ["role:brute", "heated_body", "condition:swallowed", "immunity:cold_fire"],
  },
  {
    monsterId: "monster.hydra",
    abilityId: "multiple_heads",
    cost: NONE,
    targeting: SELF,
    tags: ["role:boss", "reaction:opportunity_per_head", "head_regrowth", "multiattack:heads"],
    hookId: "hook.monster.passive",
  },
  {
    monsterId: "monster.cloaker",
    abilityId: "moan",
    targeting: { type: "area", shape: "sphere", sizeFt: 60 },
    save: { ability: "wis", dcSource: "fixed", fixedDc: 13 },
    tags: ["role:controller", "condition:frightened", "condition:incapacitated", "false_appearance"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.assassin",
    abilityId: "assassinate",
    damage: { dice: "1d6+3+7d6", type: "piercing_poison" },
    tags: ["role:striker", "advantage:surprised_target", "critical:on_surprised_hit", "poison:save_con"],
  },
  {
    monsterId: "monster.berserker",
    abilityId: "greataxe",
    damage: { dice: "1d12+3", type: "slashing" },
    tags: ["role:soldier", "attack:melee_weapon", "attack_bonus:+5", "reckless"],
  },
  {
    monsterId: "monster.knight",
    abilityId: "leadership",
    targeting: { type: "area", shape: "sphere", sizeFt: 30 },
    tags: ["role:leader", "ally_bonus:attack_and_save:1d4", "duration:1_minute", "recharge:short_rest"],
    hookId: "hook.monster.utility",
  },
  {
    monsterId: "monster.veteran",
    abilityId: "multiattack",
    damage: { dice: "2d8+3", type: "slashing" },
    tags: ["role:soldier", "multiattack:longsword:2", "backup:shortsword", "heavy_crossbow"],
    hookId: "hook.monster.multiattack",
  },
  {
    monsterId: "monster.gladiator",
    abilityId: "shield_bash",
    damage: { dice: "2d6+4", type: "bludgeoning" },
    save: { ability: "str", dcSource: "fixed", fixedDc: 15 },
    tags: ["role:elite_soldier", "condition:prone", "parry:reaction", "multiattack:spear_shield_bash"],
  },
  {
    monsterId: "monster.bandit_captain",
    abilityId: "multiattack",
    damage: { dice: "1d6+3", type: "slashing_piercing" },
    tags: ["role:leader", "multiattack:scimitar_dagger", "parry:reaction"],
    hookId: "hook.monster.multiattack",
  },
  {
    monsterId: "monster.archmage",
    abilityId: "spell_burst",
    targeting: { type: "creature", rangeFt: 120 },
    damage: { dice: "8d6", type: "fire_lightning_force" },
    tags: ["role:spellcaster", "spell_list:archmage", "spell_slot:limited", "defense:globe_or_shield"],
    hookId: "hook.monster.spell",
  },
  {
    monsterId: "monster.scout",
    abilityId: "longbow",
    targeting: { type: "creature", rangeFt: 150 },
    damage: { dice: "1d8+2", type: "piercing" },
    tags: ["role:skirmisher", "attack:ranged_weapon", "attack_bonus:+4", "range_long:600", "mobility:hide"],
  },
  {
    monsterId: "monster.spy",
    abilityId: "sneak_attack",
    damage: { dice: "1d6+2+2d6", type: "piercing" },
    tags: ["role:striker", "sneak_attack:2d6", "cunning_action", "social:deception"],
  },
  {
    monsterId: "monster.thug",
    abilityId: "mace",
    damage: { dice: "1d6+2", type: "bludgeoning" },
    tags: ["role:minion", "pack_tactics", "multiattack:mace:2"],
  },
];

export const P4_MONSTER_ABILITY_DEFINITIONS: RuleCatalogEntry[] =
  P4_MONSTER_SEEDS.map(ability);
