import {
  RuleCatalogEntry,
  RuleCost,
  RuleTargeting,
} from "./rule-catalog.types";

type P4SpellOptions = {
  level: number;
  cost?: RuleCost;
  targeting: RuleTargeting;
  damage?: RuleCatalogEntry["damage"];
  duration?: RuleCatalogEntry["duration"];
  concentration?: boolean;
  save?: RuleCatalogEntry["save"];
  tags: string[];
  scaling?: RuleCatalogEntry["scaling"];
};

const ACTION: RuleCost = { type: "action" };
const SELF: RuleTargeting = { type: "self" };

function p4Spell(id: string, options: P4SpellOptions): RuleCatalogEntry {
  return {
    id: `spell.${id}`,
    kind: "spell_definitions",
    source: "SRD5E",
    levelRequirement: {},
    trigger:
      options.cost?.type === "bonus_action"
        ? "bonus_action"
        : options.cost?.type === "reaction"
          ? "reaction"
          : "action",
    cost: options.cost ?? ACTION,
    targeting: options.targeting,
    save: options.save ?? null,
    damage: options.damage ?? null,
    duration: options.duration ?? null,
    concentration: options.concentration ?? false,
    scaling: options.scaling ?? null,
    runtimeEffect: {
      type: "spell",
      tags: [`spell_level:${options.level}`, "p4_content", ...options.tags],
      hookId: `hook.spell.cast_${id}`,
    },
  };
}

export const P4_SPELL_DEFINITIONS: RuleCatalogEntry[] = [
  p4Spell("banishment", {
    level: 4,
    targeting: { type: "creature", rangeFt: 60 },
    save: { ability: "cha", dcSource: "spell_save_dc" },
    duration: { unit: "minute", amount: 1 },
    concentration: true,
    tags: ["save:cha", "condition:banished", "target:native_plane_or_extraplanar"],
    scaling: { mode: "slot_level", table: { mode: "target_count", count: 1, perSlotAbove: 1 } },
  }),
  p4Spell("black_tentacles", {
    level: 4,
    targeting: { type: "area", shape: "cube", sizeFt: 20 },
    save: { ability: "dex", dcSource: "spell_save_dc" },
    damage: { dice: "3d6", type: "bludgeoning" },
    duration: { unit: "minute", amount: 1 },
    concentration: true,
    tags: ["terrain:difficult", "condition:restrained", "escape:ability_check"],
  }),
  p4Spell("confusion", {
    level: 4,
    targeting: { type: "area", shape: "sphere", sizeFt: 10 },
    save: { ability: "wis", dcSource: "spell_save_dc" },
    duration: { unit: "minute", amount: 1 },
    concentration: true,
    tags: ["save:wis", "condition:confused", "random_behavior_table"],
    scaling: { mode: "slot_level", table: { mode: "area_radius", feet: 5, perSlotAbove: 1 } },
  }),
  p4Spell("conjure_minor_elementals", {
    level: 4,
    targeting: { type: "area", shape: "sphere", sizeFt: 90 },
    duration: { unit: "hour", amount: 1 },
    concentration: true,
    tags: ["summon:minor_elementals", "token_lifecycle:concentration", "owner_action_economy:gm"],
  }),
  p4Spell("conjure_woodland_beings", {
    level: 4,
    targeting: { type: "area", shape: "sphere", sizeFt: 60 },
    duration: { unit: "hour", amount: 1 },
    concentration: true,
    tags: ["summon:fey", "token_lifecycle:concentration", "owner_action_economy:gm"],
  }),
  p4Spell("control_water", {
    level: 4,
    targeting: { type: "area", shape: "cube", sizeFt: 100 },
    duration: { unit: "minute", amount: 10 },
    concentration: true,
    tags: ["environment:water", "option:flood", "option:part_water", "option:redirect_flow", "option:whirlpool"],
  }),
  p4Spell("fabricate", {
    level: 4,
    targeting: { type: "area", shape: "cube", sizeFt: 10 },
    duration: { unit: "instant", amount: null },
    tags: ["crafting:convert_raw_materials", "tool_proficiency:required_for_fine_work"],
  }),
  p4Spell("fire_shield", {
    level: 4,
    targeting: SELF,
    damage: { dice: "2d8", type: "fire_or_cold" },
    duration: { unit: "minute", amount: 10 },
    tags: ["resistance:cold_or_fire", "retaliation_damage:2d8", "light:bright:10"],
  }),
  p4Spell("greater_invisibility", {
    level: 4,
    targeting: { type: "creature", rangeFt: 5 },
    duration: { unit: "minute", amount: 1 },
    concentration: true,
    tags: ["condition:invisible", "does_not_end_on_attack_or_spell"],
  }),
  p4Spell("guardian_of_faith", {
    level: 4,
    targeting: { type: "area", shape: "cube", sizeFt: 10 },
    save: { ability: "dex", dcSource: "spell_save_dc" },
    damage: { dice: "20", type: "radiant" },
    duration: { unit: "hour", amount: 8 },
    tags: ["summon:guardian", "trigger:hostile_enters", "damage_cap:60", "half_damage_on_success"],
  }),
  p4Spell("hallucinatory_terrain", {
    level: 4,
    targeting: { type: "area", shape: "cube", sizeFt: 150 },
    duration: { unit: "hour", amount: 24 },
    tags: ["illusion:terrain", "investigation_reveals", "map_overlay:illusory"],
  }),
  p4Spell("polymorph", {
    level: 4,
    targeting: { type: "creature", rangeFt: 60 },
    save: { ability: "wis", dcSource: "spell_save_dc" },
    duration: { unit: "hour", amount: 1 },
    concentration: true,
    tags: ["transform:beast", "replace_stats", "hp_pool:beast_form"],
  }),
  p4Spell("resilient_sphere", {
    level: 4,
    targeting: { type: "creature", rangeFt: 30 },
    save: { ability: "dex", dcSource: "spell_save_dc" },
    duration: { unit: "minute", amount: 1 },
    concentration: true,
    tags: ["condition:contained", "barrier:immune_damage", "blocks_effects"],
  }),
  p4Spell("stoneskin", {
    level: 4,
    targeting: { type: "creature", rangeFt: 5 },
    duration: { unit: "hour", amount: 1 },
    concentration: true,
    tags: ["resistance:bludgeoning", "resistance:piercing", "resistance:slashing", "source:nonmagical"],
  }),

  p4Spell("animate_objects", {
    level: 5,
    targeting: { type: "area", shape: "cube", sizeFt: 120 },
    duration: { unit: "minute", amount: 1 },
    concentration: true,
    tags: ["summon:animated_objects", "token_lifecycle:concentration", "object_size_budget"],
  }),
  p4Spell("cloudkill", {
    level: 5,
    targeting: { type: "area", shape: "sphere", sizeFt: 20 },
    save: { ability: "con", dcSource: "spell_save_dc" },
    damage: { dice: "5d8", type: "poison", scaling: "slot_level" },
    duration: { unit: "minute", amount: 10 },
    concentration: true,
    tags: ["save:con", "damage:poison", "terrain:heavily_obscured", "moves_away:10ft"],
    scaling: { mode: "slot_level", table: { mode: "damage_dice", dice: "1d8", perSlotAbove: 1 } },
  }),
  p4Spell("cone_of_cold", {
    level: 5,
    targeting: { type: "area", shape: "cone", sizeFt: 60 },
    save: { ability: "con", dcSource: "spell_save_dc" },
    damage: { dice: "8d8", type: "cold", scaling: "slot_level" },
    duration: { unit: "instant", amount: null },
    tags: ["save:con", "damage:cold", "half_damage_on_success"],
    scaling: { mode: "slot_level", table: { mode: "damage_dice", dice: "1d8", perSlotAbove: 1 } },
  }),
  p4Spell("conjure_elemental", {
    level: 5,
    targeting: { type: "area", shape: "cube", sizeFt: 10 },
    duration: { unit: "hour", amount: 1 },
    concentration: true,
    tags: ["summon:elemental", "token_lifecycle:concentration", "loss_of_control:on_concentration_break"],
  }),
  p4Spell("dominate_person", {
    level: 5,
    targeting: { type: "creature", rangeFt: 60 },
    save: { ability: "wis", dcSource: "spell_save_dc" },
    duration: { unit: "minute", amount: 1 },
    concentration: true,
    tags: ["condition:charmed", "control:humanoid", "repeat_save:on_damage"],
    scaling: { mode: "slot_level", table: { mode: "duration_step", 6: "10m", 7: "1h", 8: "8h" } },
  }),
  p4Spell("flame_strike", {
    level: 5,
    targeting: { type: "area", shape: "sphere", sizeFt: 10 },
    save: { ability: "dex", dcSource: "spell_save_dc" },
    damage: { dice: "4d6+4d6", type: "fire_radiant", scaling: "slot_level" },
    duration: { unit: "instant", amount: null },
    tags: ["area:cylinder", "save:dex", "damage:fire", "damage:radiant", "half_damage_on_success"],
    scaling: { mode: "slot_level", table: { mode: "damage_dice", dice: "1d6", perSlotAbove: 1 } },
  }),
  p4Spell("greater_restoration", {
    level: 5,
    targeting: { type: "creature", rangeFt: 5 },
    duration: { unit: "instant", amount: null },
    tags: ["remove:charmed", "remove:petrified", "remove:curse", "remove:ability_reduction", "component:diamond_dust:100gp"],
  }),
  p4Spell("hold_monster", {
    level: 5,
    targeting: { type: "creature", rangeFt: 90 },
    save: { ability: "wis", dcSource: "spell_save_dc" },
    duration: { unit: "minute", amount: 1 },
    concentration: true,
    tags: ["condition:paralyzed", "save:wis:end_turn", "target:not_undead"],
    scaling: { mode: "slot_level", table: { mode: "target_count", count: 1, perSlotAbove: 1 } },
  }),
  p4Spell("insect_plague", {
    level: 5,
    targeting: { type: "area", shape: "sphere", sizeFt: 20 },
    save: { ability: "con", dcSource: "spell_save_dc" },
    damage: { dice: "4d10", type: "piercing", scaling: "slot_level" },
    duration: { unit: "minute", amount: 10 },
    concentration: true,
    tags: ["terrain:lightly_obscured", "terrain:difficult", "save:con", "half_damage_on_success"],
    scaling: { mode: "slot_level", table: { mode: "damage_dice", dice: "1d10", perSlotAbove: 1 } },
  }),
  p4Spell("mass_cure_wounds", {
    level: 5,
    targeting: { type: "area", shape: "sphere", sizeFt: 30 },
    damage: { dice: "3d8", type: "healing", scaling: "slot_level" },
    duration: { unit: "instant", amount: null },
    tags: ["healing:multi_target:6", "target:not_undead_construct"],
    scaling: { mode: "slot_level", table: { mode: "damage_dice", dice: "1d8", perSlotAbove: 1 } },
  }),
  p4Spell("mislead", {
    level: 5,
    targeting: SELF,
    duration: { unit: "hour", amount: 1 },
    concentration: true,
    tags: ["condition:invisible", "illusion:duplicate", "sense_through_duplicate"],
  }),
  p4Spell("modify_memory", {
    level: 5,
    targeting: { type: "creature", rangeFt: 30 },
    save: { ability: "wis", dcSource: "spell_save_dc" },
    duration: { unit: "minute", amount: 1 },
    concentration: true,
    tags: ["condition:charmed", "memory:rewrite:10_minutes"],
    scaling: { mode: "slot_level", table: { mode: "memory_window", 6: "7d", 7: "30d", 8: "1y", 9: "any" } },
  }),
  p4Spell("passwall", {
    level: 5,
    targeting: { type: "area", shape: "cube", sizeFt: 5 },
    duration: { unit: "hour", amount: 1 },
    tags: ["terrain:create_passage", "object:wood_plaster_stone", "passage_depth:20ft"],
  }),
  p4Spell("raise_dead", {
    level: 5,
    targeting: { type: "creature", rangeFt: 5 },
    duration: { unit: "instant", amount: null },
    tags: ["revive:hp:1", "death_window:day:10", "component:diamond:500gp", "penalty:resurrection_sickness"],
  }),
  p4Spell("scrying", {
    level: 5,
    targeting: { type: "creature", rangeFt: null },
    save: { ability: "wis", dcSource: "spell_save_dc" },
    duration: { unit: "minute", amount: 10 },
    concentration: true,
    tags: ["sensor:invisible", "range:same_plane", "target:creature_or_location"],
  }),
  p4Spell("telekinesis", {
    level: 5,
    targeting: { type: "creature", rangeFt: 60 },
    duration: { unit: "minute", amount: 10 },
    concentration: true,
    tags: ["contested_check:spellcasting_vs_str", "move:creature_or_object", "restrain:creature"],
  }),
  p4Spell("teleportation_circle", {
    level: 5,
    targeting: { type: "area", shape: "sphere", sizeFt: 10 },
    duration: { unit: "round", amount: 1 },
    tags: ["teleport:circle", "destination:sigil_sequence", "map_transition"],
  }),
  p4Spell("wall_of_force", {
    level: 5,
    targeting: { type: "area", shape: "sphere", sizeFt: 10 },
    duration: { unit: "minute", amount: 10 },
    concentration: true,
    tags: ["wall:force", "immune:damage", "blocks:physical", "destroyed_by:disintegrate"],
  }),
  p4Spell("wall_of_stone", {
    level: 5,
    targeting: { type: "area", shape: "cube", sizeFt: 10 },
    duration: { unit: "minute", amount: 10 },
    concentration: true,
    tags: ["wall:stone", "object:panels", "can_become_permanent"],
  }),

  p4Spell("chain_lightning", {
    level: 6,
    targeting: { type: "creature", rangeFt: 150 },
    save: { ability: "dex", dcSource: "spell_save_dc" },
    damage: { dice: "10d8", type: "lightning" },
    duration: { unit: "instant", amount: null },
    tags: ["target_count:4", "save:dex", "half_damage_on_success"],
  }),
  p4Spell("circle_of_death", {
    level: 6,
    targeting: { type: "area", shape: "sphere", sizeFt: 60 },
    save: { ability: "con", dcSource: "spell_save_dc" },
    damage: { dice: "8d6", type: "necrotic", scaling: "slot_level" },
    duration: { unit: "instant", amount: null },
    tags: ["save:con", "damage:necrotic", "half_damage_on_success"],
    scaling: { mode: "slot_level", table: { mode: "damage_dice", dice: "2d6", perSlotAbove: 1 } },
  }),
  p4Spell("disintegrate", {
    level: 6,
    targeting: { type: "creature", rangeFt: 60 },
    save: { ability: "dex", dcSource: "spell_save_dc" },
    damage: { dice: "10d6+40", type: "force", scaling: "slot_level" },
    duration: { unit: "instant", amount: null },
    tags: ["save:dex", "damage:force", "destroy_if_zero_hp", "object:destroy_large_or_smaller"],
    scaling: { mode: "slot_level", table: { mode: "damage_dice", dice: "3d6", perSlotAbove: 1 } },
  }),
  p4Spell("find_the_path", {
    level: 6,
    targeting: SELF,
    duration: { unit: "day", amount: 1 },
    concentration: true,
    tags: ["navigation:shortest_route", "destination:same_plane", "exploration:map_guidance"],
  }),
  p4Spell("flesh_to_stone", {
    level: 6,
    targeting: { type: "creature", rangeFt: 60 },
    save: { ability: "con", dcSource: "spell_save_dc" },
    duration: { unit: "minute", amount: 1 },
    concentration: true,
    tags: ["condition:restrained", "condition:petrified", "save_sequence:three_failures_or_successes"],
  }),
  p4Spell("globe_of_invulnerability", {
    level: 6,
    targeting: SELF,
    duration: { unit: "minute", amount: 1 },
    concentration: true,
    tags: ["aura:10", "block:spell_level_5_or_lower", "upcast:blocks_higher_level"],
  }),
  p4Spell("harm", {
    level: 6,
    targeting: { type: "creature", rangeFt: 60 },
    save: { ability: "con", dcSource: "spell_save_dc" },
    damage: { dice: "14d6", type: "necrotic" },
    duration: { unit: "instant", amount: null },
    tags: ["save:con", "max_hp_reduction:until_long_rest", "cannot_reduce_below_1"],
  }),
  p4Spell("heal", {
    level: 6,
    targeting: { type: "creature", rangeFt: 60 },
    damage: { dice: "70", type: "healing", scaling: "slot_level" },
    duration: { unit: "instant", amount: null },
    tags: ["healing:70", "remove:blindness", "remove:deafness", "remove:disease"],
    scaling: { mode: "slot_level", table: { mode: "flat_bonus", amount: 10, perSlotAbove: 1 } },
  }),
  p4Spell("heroes_feast", {
    level: 6,
    targeting: { type: "area", shape: "sphere", sizeFt: 10 },
    duration: { unit: "day", amount: 1 },
    tags: ["feast:12_creatures", "immunity:poison", "immunity:frightened", "max_hp_bonus:2d10"],
  }),
  p4Spell("move_earth", {
    level: 6,
    targeting: { type: "area", shape: "cube", sizeFt: 40 },
    duration: { unit: "hour", amount: 2 },
    concentration: true,
    tags: ["terrain:reshape_earth", "downtime:excavation", "map_edit:soft_earth"],
  }),
  p4Spell("sunbeam", {
    level: 6,
    targeting: { type: "area", shape: "line", sizeFt: 60 },
    save: { ability: "con", dcSource: "spell_save_dc" },
    damage: { dice: "6d8", type: "radiant" },
    duration: { unit: "minute", amount: 1 },
    concentration: true,
    tags: ["save:con", "condition:blinded", "repeatable:action_each_turn", "undead_ooze_disadvantage"],
  }),
  p4Spell("true_seeing", {
    level: 6,
    targeting: { type: "creature", rangeFt: 5 },
    duration: { unit: "hour", amount: 1 },
    tags: ["sense:truesight:120", "see:secret_doors", "see:ethereal_plane"],
  }),
  p4Spell("wall_of_ice", {
    level: 6,
    targeting: { type: "area", shape: "sphere", sizeFt: 10 },
    save: { ability: "dex", dcSource: "spell_save_dc" },
    damage: { dice: "10d6", type: "cold", scaling: "slot_level" },
    duration: { unit: "minute", amount: 10 },
    concentration: true,
    tags: ["wall:ice", "damage:on_create", "terrain:cold_air_after_destroyed"],
    scaling: { mode: "slot_level", table: { mode: "damage_dice", dice: "2d6", perSlotAbove: 1 } },
  }),
  p4Spell("word_of_recall", {
    level: 6,
    targeting: { type: "area", shape: "sphere", sizeFt: 5 },
    duration: { unit: "instant", amount: null },
    tags: ["teleport:sanctuary", "target_count:6", "map_transition"],
  }),
  p4Spell("arcane_gate", {
    level: 6,
    targeting: { type: "area", shape: "sphere", sizeFt: 10 },
    duration: { unit: "minute", amount: 10 },
    concentration: true,
    tags: ["teleport:linked_portals", "range:500ft", "orientation:one_way_choice"],
  }),
  p4Spell("eyebite", {
    level: 6,
    targeting: { type: "creature", rangeFt: 60 },
    save: { ability: "wis", dcSource: "spell_save_dc" },
    duration: { unit: "minute", amount: 1 },
    concentration: true,
    tags: ["option:asleep", "option:panicked", "option:sickened", "repeatable:action_each_turn"],
  }),
  p4Spell("mass_suggestion", {
    level: 6,
    targeting: { type: "creature", rangeFt: 60 },
    save: { ability: "wis", dcSource: "spell_save_dc" },
    duration: { unit: "hour", amount: 24 },
    tags: ["target_count:12", "condition:charmed_command", "language:understands"],
    scaling: { mode: "slot_level", table: { mode: "duration_step", 7: "10d", 8: "30d", 9: "365d" } },
  }),
];
