import {
  RuleCatalogEntry,
  RuleCost,
  RuleTargeting,
} from "./rule-catalog.types";

type P5MonsterSeed = {
  monsterId: string;
  abilityId: string;
  cost?: RuleCost;
  targeting?: RuleTargeting;
  save?: RuleCatalogEntry["save"];
  damage?: RuleCatalogEntry["damage"];
  tags: string[];
  hookId?: string;
};

const ACTION: RuleCost = { type: "action" };
const NONE: RuleCost = { type: "none" };
const SELF: RuleTargeting = { type: "self" };

export const P5_EXECUTABLE_MONSTER_IDS = [
  "monster.adult_black_dragon",
  "monster.adult_blue_dragon",
  "monster.adult_green_dragon",
  "monster.adult_red_dragon",
  "monster.adult_white_dragon",
  "monster.ancient_black_dragon",
  "monster.ancient_blue_dragon",
  "monster.ancient_green_dragon",
  "monster.ancient_red_dragon",
  "monster.ancient_white_dragon",
  "monster.cloud_giant",
  "monster.storm_giant",
  "monster.treant",
  "monster.roc",
  "monster.kraken",
  "monster.balor",
  "monster.pit_fiend",
  "monster.marilith",
  "monster.nalfeshnee",
  "monster.vrock",
  "monster.hezrou",
  "monster.goristro",
  "monster.horned_devil",
  "monster.ice_devil",
  "monster.bone_devil",
  "monster.bearded_devil",
  "monster.chain_devil",
  "monster.erinyes",
  "monster.solar",
  "monster.planetar",
  "monster.deva",
  "monster.androsphinx",
  "monster.gynosphinx",
  "monster.couatl",
  "monster.unicorn",
  "monster.death_knight",
  "monster.demilich",
  "monster.wraith",
  "monster.banshee",
  "monster.flameskull",
  "monster.shield_guardian",
  "monster.helmed_horror",
  "monster.flesh_golem",
  "monster.clay_golem",
  "monster.iron_golem",
  "monster.djinni",
  "monster.efreeti",
  "monster.dao",
  "monster.marid",
  "monster.galeb_duhr",
  "monster.sahuagin_baron",
  "monster.sahuagin_priestess",
  "monster.aboleth",
  "monster.remorhaz_elder",
  "monster.giant_ape",
  "monster.mammoth",
  "monster.saber_toothed_tiger",
  "monster.rhinoceros",
  "monster.elephant",
  "monster.carrion_crawler",
  "monster.otyugh",
  "monster.rust_monster",
  "monster.displacer_beast",
  "monster.ettercap",
  "monster.drider",
  "monster.drow_mage",
  "monster.drow_priestess",
  "monster.yuan_ti_abomination",
  "monster.yuan_ti_malison",
  "monster.lamia",
  "monster.rakshasa",
  "monster.mind_flayer",
  "monster.beholder",
  "monster.beholder_zombie",
  "monster.dragon_turtle",
  "monster.merfolk_champion",
  "monster.sea_hag",
  "monster.night_hag",
  "monster.green_hag",
  "monster.tarrasque",
] as const;

function ability(seed: P5MonsterSeed): RuleCatalogEntry {
  return {
    id: `${seed.monsterId}.ability.${seed.abilityId}`,
    kind: "monster_abilities",
    source: "SRD5E",
    levelRequirement: { monsterId: seed.monsterId },
    trigger:
      seed.cost?.type === "bonus_action"
        ? "bonus_action"
        : seed.cost?.type === "reaction"
          ? "reaction"
          : seed.cost?.type === "none"
            ? "always"
            : "action",
    cost: seed.cost ?? ACTION,
    targeting: seed.targeting ?? { type: "creature", rangeFt: 5 },
    save: seed.save ?? null,
    damage: seed.damage ?? null,
    duration: null,
    concentration: false,
    scaling: null,
    runtimeEffect: {
      type: "monster_ability",
      tags: ["p5_content", ...seed.tags],
      hookId: seed.hookId ?? "hook.monster.attack",
    },
  };
}

const P5_MONSTER_SEEDS: P5MonsterSeed[] = [
  {
    monsterId: "monster.adult_black_dragon",
    abilityId: "acid_breath",
    targeting: { type: "area", shape: "line", sizeFt: 60 },
    save: { ability: "dex", dcSource: "fixed", fixedDc: 18 },
    damage: { dice: "12d8", type: "acid" },
    tags: ["role:boss", "dragon:adult", "recharge:5-6", "legendary_like:resistance:3/day", "phase:bloodied_lair"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.adult_blue_dragon",
    abilityId: "lightning_breath",
    targeting: { type: "area", shape: "line", sizeFt: 90 },
    save: { ability: "dex", dcSource: "fixed", fixedDc: 19 },
    damage: { dice: "12d10", type: "lightning" },
    tags: ["role:boss", "dragon:adult", "recharge:5-6", "legendary_like:wing_attack", "terrain:lair_lightning"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.adult_green_dragon",
    abilityId: "poison_breath",
    targeting: { type: "area", shape: "cone", sizeFt: 60 },
    save: { ability: "con", dcSource: "fixed", fixedDc: 18 },
    damage: { dice: "16d6", type: "poison" },
    tags: ["role:boss", "dragon:adult", "recharge:5-6", "condition:poisoned", "ai_goal:divide_party"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.adult_red_dragon",
    abilityId: "fire_breath",
    targeting: { type: "area", shape: "cone", sizeFt: 60 },
    save: { ability: "dex", dcSource: "fixed", fixedDc: 21 },
    damage: { dice: "18d6", type: "fire" },
    tags: ["role:boss", "dragon:adult", "recharge:5-6", "legendary_like:tail_attack", "phase:inferno"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.adult_white_dragon",
    abilityId: "cold_breath",
    targeting: { type: "area", shape: "cone", sizeFt: 60 },
    save: { ability: "con", dcSource: "fixed", fixedDc: 19 },
    damage: { dice: "12d8", type: "cold" },
    tags: ["role:boss", "dragon:adult", "recharge:5-6", "terrain:ice_lair", "movement:burrow:30"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.ancient_black_dragon",
    abilityId: "acid_breath",
    targeting: { type: "area", shape: "line", sizeFt: 90 },
    save: { ability: "dex", dcSource: "fixed", fixedDc: 22 },
    damage: { dice: "15d8", type: "acid" },
    tags: ["role:mythic_boss", "dragon:ancient", "recharge:5-6", "legendary_like:resistance:3/day", "phase:swamp_heart"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.ancient_blue_dragon",
    abilityId: "lightning_breath",
    targeting: { type: "area", shape: "line", sizeFt: 120 },
    save: { ability: "dex", dcSource: "fixed", fixedDc: 23 },
    damage: { dice: "16d10", type: "lightning" },
    tags: ["role:mythic_boss", "dragon:ancient", "recharge:5-6", "legendary_like:lair_storm", "terrain:sandstorm"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.ancient_green_dragon",
    abilityId: "poison_breath",
    targeting: { type: "area", shape: "cone", sizeFt: 90 },
    save: { ability: "con", dcSource: "fixed", fixedDc: 22 },
    damage: { dice: "22d6", type: "poison" },
    tags: ["role:mythic_boss", "dragon:ancient", "recharge:5-6", "dominate_minions", "phase:toxic_canopy"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.ancient_red_dragon",
    abilityId: "fire_breath",
    targeting: { type: "area", shape: "cone", sizeFt: 90 },
    save: { ability: "dex", dcSource: "fixed", fixedDc: 24 },
    damage: { dice: "26d6", type: "fire" },
    tags: ["role:mythic_boss", "dragon:ancient", "recharge:5-6", "legendary_like:resistance:3/day", "phase:volcanic_heart"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.ancient_white_dragon",
    abilityId: "cold_breath",
    targeting: { type: "area", shape: "cone", sizeFt: 90 },
    save: { ability: "con", dcSource: "fixed", fixedDc: 22 },
    damage: { dice: "16d8", type: "cold" },
    tags: ["role:mythic_boss", "dragon:ancient", "recharge:5-6", "terrain:blizzard", "phase:frozen_hunt"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.cloud_giant",
    abilityId: "morningstar",
    damage: { dice: "3d8+8", type: "piercing" },
    tags: ["role:brute", "attack:melee_weapon", "attack_bonus:+12", "spell_list:cloud_giant", "fog_cloud_escape"],
  },
  {
    monsterId: "monster.storm_giant",
    abilityId: "lightning_strike",
    targeting: { type: "area", shape: "line", sizeFt: 60 },
    save: { ability: "dex", dcSource: "fixed", fixedDc: 17 },
    damage: { dice: "12d8", type: "lightning" },
    tags: ["role:artillery_boss", "save:dex", "recharge:5-6", "amphibious", "terrain:storm"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.treant",
    abilityId: "animate_trees",
    targeting: { type: "area", shape: "sphere", sizeFt: 60 },
    tags: ["role:summoner", "summon:trees:2", "siege_monster", "terrain:forest"],
    hookId: "hook.monster.summon",
  },
  {
    monsterId: "monster.roc",
    abilityId: "talons",
    damage: { dice: "4d8+9", type: "slashing" },
    tags: ["role:flying_brute", "attack:melee_weapon", "attack_bonus:+13", "condition:grappled", "movement:fly:120"],
  },
  {
    monsterId: "monster.kraken",
    abilityId: "lightning_storm",
    targeting: { type: "area", shape: "sphere", sizeFt: 120 },
    save: { ability: "dex", dcSource: "fixed", fixedDc: 23 },
    damage: { dice: "4d10", type: "lightning" },
    tags: ["role:mythic_boss", "legendary_like:tentacle", "recharge:5-6", "lair:seaquake", "condition:grappled"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.balor",
    abilityId: "fire_aura",
    cost: NONE,
    targeting: SELF,
    damage: { dice: "3d6", type: "fire" },
    tags: ["role:fiend_boss", "aura:fire", "trigger:on_turn_start", "death_burst", "legendary_like:teleport"],
    hookId: "hook.monster.passive",
  },
  {
    monsterId: "monster.pit_fiend",
    abilityId: "bite",
    damage: { dice: "4d6+8+6d6", type: "piercing_poison" },
    tags: ["role:fiend_boss", "attack:melee_weapon", "attack_bonus:+14", "condition:poisoned", "fear_aura"],
  },
  {
    monsterId: "monster.marilith",
    abilityId: "reactive_multiattack",
    damage: { dice: "6d8+24", type: "slashing" },
    tags: ["role:multiattack_boss", "attack:melee_weapon", "attack_bonus:+9", "multiattack:longsword:6", "reaction:parry"],
    hookId: "hook.monster.multiattack",
  },
  {
    monsterId: "monster.nalfeshnee",
    abilityId: "horror_nimbus",
    targeting: { type: "area", shape: "sphere", sizeFt: 15 },
    save: { ability: "wis", dcSource: "fixed", fixedDc: 15 },
    tags: ["role:fiend_controller", "condition:frightened", "recharge:5-6", "teleport:120"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.vrock",
    abilityId: "spores",
    targeting: { type: "area", shape: "sphere", sizeFt: 15 },
    save: { ability: "con", dcSource: "fixed", fixedDc: 14 },
    damage: { dice: "1d10", type: "poison" },
    tags: ["role:flying_fiend", "condition:poisoned", "damage_over_time:poison:1d10", "recharge:6"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.hezrou",
    abilityId: "stench",
    cost: NONE,
    targeting: SELF,
    tags: ["role:fiend_brute", "aura:stench", "trigger:on_turn_start", "condition:poisoned", "save:con"],
    hookId: "hook.monster.passive",
  },
  {
    monsterId: "monster.goristro",
    abilityId: "gore",
    damage: { dice: "7d10+7", type: "piercing" },
    tags: ["role:fiend_brute", "attack:melee_weapon", "attack_bonus:+13", "charge:extra_damage", "condition:prone"],
  },
  {
    monsterId: "monster.horned_devil",
    abilityId: "hurl_flame",
    targeting: { type: "creature", rangeFt: 150 },
    damage: { dice: "4d6", type: "fire" },
    tags: ["role:flying_artillery", "attack:ranged_weapon", "attack_bonus:+7", "range_long:150", "infernal_wound"],
  },
  {
    monsterId: "monster.ice_devil",
    abilityId: "wall_of_ice",
    targeting: { type: "area", shape: "cube", sizeFt: 60 },
    save: { ability: "dex", dcSource: "fixed", fixedDc: 17 },
    damage: { dice: "10d6", type: "cold" },
    tags: ["role:fiend_controller", "recharge:6", "terrain:ice_wall", "condition:restrained"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.bone_devil",
    abilityId: "sting",
    damage: { dice: "2d8+4+5d6", type: "piercing_poison" },
    tags: ["role:flying_soldier", "attack:melee_weapon", "attack_bonus:+8", "condition:poisoned", "movement:fly:40"],
  },
  {
    monsterId: "monster.bearded_devil",
    abilityId: "beard",
    damage: { dice: "1d8+2", type: "piercing" },
    tags: ["role:fiend_soldier", "attack:melee_weapon", "attack_bonus:+5", "condition:poisoned", "infernal_wound"],
  },
  {
    monsterId: "monster.chain_devil",
    abilityId: "animate_chains",
    targeting: { type: "area", shape: "sphere", sizeFt: 60 },
    tags: ["role:controller", "condition:restrained", "summon:animated_chains:4", "reaction:unnerving_mask"],
    hookId: "hook.monster.summon",
  },
  {
    monsterId: "monster.erinyes",
    abilityId: "longbow",
    targeting: { type: "creature", rangeFt: 150 },
    damage: { dice: "1d8+3+3d8", type: "piercing_poison" },
    tags: ["role:flying_artillery", "attack:ranged_weapon", "attack_bonus:+7", "range_long:600", "condition:poisoned"],
  },
  {
    monsterId: "monster.solar",
    abilityId: "slaying_longbow",
    targeting: { type: "creature", rangeFt: 150 },
    save: { ability: "con", dcSource: "fixed", fixedDc: 15 },
    damage: { dice: "2d8+6+6d8", type: "piercing_radiant" },
    tags: ["role:celestial_boss", "attack:ranged_weapon", "attack_bonus:+13", "range_long:600", "condition:instant_death_threshold"],
  },
  {
    monsterId: "monster.planetar",
    abilityId: "greatsword",
    damage: { dice: "4d6+7+5d8", type: "slashing_radiant" },
    tags: ["role:celestial_soldier", "attack:melee_weapon", "attack_bonus:+12", "spell_list:divine", "healing_touch"],
  },
  {
    monsterId: "monster.deva",
    abilityId: "mace",
    damage: { dice: "1d6+4+4d8", type: "bludgeoning_radiant" },
    tags: ["role:celestial", "attack:melee_weapon", "attack_bonus:+8", "healing_touch", "shapechange"],
  },
  {
    monsterId: "monster.androsphinx",
    abilityId: "roar",
    targeting: { type: "area", shape: "sphere", sizeFt: 60 },
    save: { ability: "wis", dcSource: "fixed", fixedDc: 18 },
    tags: ["role:guardian_boss", "condition:frightened", "condition:prone", "legendary_like:roar_sequence"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.gynosphinx",
    abilityId: "spell_riddle",
    targeting: { type: "creature", rangeFt: 120 },
    save: { ability: "int", dcSource: "fixed", fixedDc: 16 },
    damage: { dice: "6d8", type: "psychic" },
    tags: ["role:guardian_spellcaster", "spell_list:sphinx", "teleport:lair", "condition:charmed"],
    hookId: "hook.monster.spell",
  },
  {
    monsterId: "monster.couatl",
    abilityId: "bite",
    damage: { dice: "1d6+5", type: "piercing" },
    tags: ["role:celestial_controller", "attack:melee_weapon", "attack_bonus:+8", "condition:poisoned", "condition:unconscious"],
  },
  {
    monsterId: "monster.unicorn",
    abilityId: "healing_touch",
    targeting: { type: "creature", rangeFt: 5 },
    damage: { dice: "2d8+2", type: "healing" },
    tags: ["role:celestial_support", "usage:3/day", "teleport:1/day", "aura:magic_resistance"],
    hookId: "hook.monster.utility",
  },
  {
    monsterId: "monster.death_knight",
    abilityId: "hellfire_orb",
    targeting: { type: "area", shape: "sphere", sizeFt: 20 },
    save: { ability: "dex", dcSource: "fixed", fixedDc: 18 },
    damage: { dice: "10d6+10d6", type: "fire_necrotic" },
    tags: ["role:undead_boss", "usage:1/day", "spell_list:death_knight", "marshal_undead"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.demilich",
    abilityId: "howl",
    targeting: { type: "area", shape: "sphere", sizeFt: 30 },
    save: { ability: "con", dcSource: "fixed", fixedDc: 15 },
    tags: ["role:undead_boss", "condition:drop_to_zero_hp", "recharge:5-6", "legendary_like:life_drain"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.wraith",
    abilityId: "life_drain",
    damage: { dice: "4d8+3", type: "necrotic" },
    tags: ["role:undead_skirmisher", "attack:melee_weapon", "attack_bonus:+6", "effect:max_hp_reduction", "summon:specter"],
  },
  {
    monsterId: "monster.banshee",
    abilityId: "wail",
    targeting: { type: "area", shape: "sphere", sizeFt: 30 },
    save: { ability: "con", dcSource: "fixed", fixedDc: 13 },
    tags: ["role:undead_controller", "condition:drop_to_zero_hp", "usage:1/day", "condition:frightened"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.flameskull",
    abilityId: "fireball",
    targeting: { type: "area", shape: "sphere", sizeFt: 20 },
    save: { ability: "dex", dcSource: "fixed", fixedDc: 13 },
    damage: { dice: "8d6", type: "fire" },
    tags: ["role:undead_spellcaster", "spell:spell.fireball", "rejuvenation", "spell_list:flameskull"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.shield_guardian",
    abilityId: "bound_guardian",
    cost: NONE,
    targeting: SELF,
    tags: ["role:construct_guardian", "aura:bound_guardian", "trigger:on_turn_start", "damage_redirect", "regeneration:10"],
    hookId: "hook.monster.passive",
  },
  {
    monsterId: "monster.helmed_horror",
    abilityId: "longsword",
    damage: { dice: "1d8+4", type: "slashing" },
    tags: ["role:construct_soldier", "attack:melee_weapon", "attack_bonus:+6", "multiattack:longsword:2", "spell_immunity:selected"],
    hookId: "hook.monster.multiattack",
  },
  {
    monsterId: "monster.flesh_golem",
    abilityId: "slam",
    damage: { dice: "2d8+4", type: "bludgeoning" },
    tags: ["role:construct_brute", "attack:melee_weapon", "attack_bonus:+7", "berserk", "lightning_absorption"],
  },
  {
    monsterId: "monster.clay_golem",
    abilityId: "haste",
    targeting: SELF,
    tags: ["role:construct_brute", "recharge:5-6", "multiattack:slam:2", "condition:haste_like", "immunity:acid"],
    hookId: "hook.monster.utility",
  },
  {
    monsterId: "monster.iron_golem",
    abilityId: "poison_breath",
    targeting: { type: "area", shape: "cone", sizeFt: 15 },
    save: { ability: "con", dcSource: "fixed", fixedDc: 19 },
    damage: { dice: "10d8", type: "poison" },
    tags: ["role:construct_boss", "recharge:6", "immunity:fire_healing", "multiattack:slam:2"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.djinni",
    abilityId: "whirlwind",
    targeting: { type: "area", shape: "sphere", sizeFt: 10 },
    save: { ability: "str", dcSource: "fixed", fixedDc: 18 },
    damage: { dice: "3d6+2", type: "bludgeoning" },
    tags: ["role:elemental_controller", "movement:fly:90", "condition:restrained", "spell_list:djinni"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.efreeti",
    abilityId: "hurl_flame",
    targeting: { type: "creature", rangeFt: 120 },
    damage: { dice: "5d6", type: "fire" },
    tags: ["role:elemental_artillery", "attack:ranged_weapon", "attack_bonus:+7", "range_long:120", "spell_list:efreeti"],
  },
  {
    monsterId: "monster.dao",
    abilityId: "maul",
    damage: { dice: "4d6+6", type: "bludgeoning" },
    tags: ["role:elemental_brute", "attack:melee_weapon", "attack_bonus:+10", "earth_glide", "spell_list:dao"],
  },
  {
    monsterId: "monster.marid",
    abilityId: "water_jet",
    targeting: { type: "area", shape: "line", sizeFt: 60 },
    save: { ability: "dex", dcSource: "fixed", fixedDc: 16 },
    damage: { dice: "4d6", type: "bludgeoning" },
    tags: ["role:elemental_controller", "forced_movement:push:20", "condition:prone", "spell_list:marid"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.galeb_duhr",
    abilityId: "animate_boulders",
    targeting: { type: "area", shape: "sphere", sizeFt: 60 },
    tags: ["role:earth_summoner", "summon:boulders:2", "false_appearance", "rolling_charge"],
    hookId: "hook.monster.summon",
  },
  {
    monsterId: "monster.sahuagin_baron",
    abilityId: "trident",
    damage: { dice: "2d6+4", type: "piercing" },
    tags: ["role:aquatic_leader", "attack:melee_weapon", "attack_bonus:+7", "multiattack:trident_bite", "blood_frenzy"],
  },
  {
    monsterId: "monster.sahuagin_priestess",
    abilityId: "spiritual_weapon",
    targeting: { type: "creature", rangeFt: 60 },
    damage: { dice: "1d8+3", type: "force" },
    tags: ["role:aquatic_spellcaster", "spell:spell.spiritual_weapon", "spell_list:sahuagin_priestess", "blood_frenzy"],
    hookId: "hook.monster.spell",
  },
  {
    monsterId: "monster.aboleth",
    abilityId: "enslave",
    targeting: { type: "creature", rangeFt: 30 },
    save: { ability: "wis", dcSource: "fixed", fixedDc: 14 },
    tags: ["role:aquatic_controller", "condition:charmed", "telepathy", "lair:mucous_cloud"],
    hookId: "hook.monster.save_condition",
  },
  {
    monsterId: "monster.remorhaz_elder",
    abilityId: "swallow",
    damage: { dice: "6d10+7+3d6", type: "piercing_fire" },
    tags: ["role:burrowing_brute", "attack:melee_weapon", "attack_bonus:+11", "condition:swallowed", "heated_body"],
  },
  {
    monsterId: "monster.giant_ape",
    abilityId: "rock",
    targeting: { type: "creature", rangeFt: 50 },
    damage: { dice: "7d6+6", type: "bludgeoning" },
    tags: ["role:brute_artillery", "attack:ranged_weapon", "attack_bonus:+9", "range_long:100", "multiattack:fist:2"],
  },
  {
    monsterId: "monster.mammoth",
    abilityId: "trampling_charge",
    damage: { dice: "4d8+7", type: "bludgeoning" },
    save: { ability: "str", dcSource: "fixed", fixedDc: 18 },
    tags: ["role:brute", "attack:melee_weapon", "attack_bonus:+10", "condition:prone", "bonus_action:stomp"],
  },
  {
    monsterId: "monster.saber_toothed_tiger",
    abilityId: "pounce",
    damage: { dice: "1d10+5", type: "piercing" },
    save: { ability: "str", dcSource: "fixed", fixedDc: 14 },
    tags: ["role:skirmisher", "attack:melee_weapon", "attack_bonus:+6", "condition:prone", "bonus_action:bite"],
  },
  {
    monsterId: "monster.rhinoceros",
    abilityId: "charge",
    damage: { dice: "2d8+5", type: "bludgeoning" },
    save: { ability: "str", dcSource: "fixed", fixedDc: 15 },
    tags: ["role:brute", "attack:melee_weapon", "attack_bonus:+7", "condition:prone", "charge:extra_damage"],
  },
  {
    monsterId: "monster.elephant",
    abilityId: "gore",
    damage: { dice: "3d8+6", type: "piercing" },
    tags: ["role:brute", "attack:melee_weapon", "attack_bonus:+8", "condition:prone", "bonus_action:trample"],
  },
  {
    monsterId: "monster.carrion_crawler",
    abilityId: "tentacles",
    damage: { dice: "1d4+2", type: "poison" },
    save: { ability: "con", dcSource: "fixed", fixedDc: 13 },
    tags: ["role:controller", "attack:melee_weapon", "attack_bonus:+8", "condition:poisoned", "condition:paralyzed"],
  },
  {
    monsterId: "monster.otyugh",
    abilityId: "tentacle_slam",
    damage: { dice: "1d8+3", type: "bludgeoning" },
    save: { ability: "con", dcSource: "fixed", fixedDc: 15 },
    tags: ["role:controller", "attack:melee_weapon", "attack_bonus:+6", "condition:grappled", "disease:bite"],
  },
  {
    monsterId: "monster.rust_monster",
    abilityId: "antennae",
    targeting: { type: "creature", rangeFt: 5 },
    tags: ["role:item_hazard", "corrode:nonmagical_metal", "equipment_damage", "attack:melee_weapon", "attack_bonus:+3"],
  },
  {
    monsterId: "monster.displacer_beast",
    abilityId: "tentacle",
    damage: { dice: "1d6+4", type: "bludgeoning_piercing" },
    tags: ["role:skirmisher", "attack:melee_weapon", "attack_bonus:+6", "displacement", "avoidance"],
  },
  {
    monsterId: "monster.ettercap",
    abilityId: "web",
    targeting: { type: "creature", rangeFt: 30 },
    save: { ability: "str", dcSource: "fixed", fixedDc: 11 },
    tags: ["role:ambusher", "attack:ranged_weapon", "attack_bonus:+4", "range_long:60", "condition:restrained"],
  },
  {
    monsterId: "monster.drider",
    abilityId: "faerie_fire",
    targeting: { type: "area", shape: "cube", sizeFt: 20 },
    save: { ability: "dex", dcSource: "fixed", fixedDc: 13 },
    tags: ["role:spellcaster_skirmisher", "spell:spell.faerie_fire", "condition:outlined", "spider_climb"],
    hookId: "hook.monster.spell",
  },
  {
    monsterId: "monster.drow_mage",
    abilityId: "lightning_bolt",
    targeting: { type: "area", shape: "line", sizeFt: 100 },
    save: { ability: "dex", dcSource: "fixed", fixedDc: 14 },
    damage: { dice: "8d6", type: "lightning" },
    tags: ["role:spellcaster", "spell:spell.lightning_bolt", "spell_list:drow_mage", "condition:invisible"],
    hookId: "hook.monster.spell",
  },
  {
    monsterId: "monster.drow_priestess",
    abilityId: "insect_plague",
    targeting: { type: "area", shape: "sphere", sizeFt: 20 },
    save: { ability: "con", dcSource: "fixed", fixedDc: 14 },
    damage: { dice: "4d10", type: "piercing" },
    tags: ["role:divine_spellcaster", "spell:spell.insect_plague", "spell_list:drow_priestess", "summon:demon"],
    hookId: "hook.monster.spell",
  },
  {
    monsterId: "monster.yuan_ti_abomination",
    abilityId: "constrict",
    damage: { dice: "2d6+4", type: "bludgeoning" },
    tags: ["role:controller_brute", "attack:melee_weapon", "attack_bonus:+7", "condition:grappled", "magic_resistance"],
  },
  {
    monsterId: "monster.yuan_ti_malison",
    abilityId: "suggestion",
    targeting: { type: "creature", rangeFt: 30 },
    save: { ability: "wis", dcSource: "fixed", fixedDc: 13 },
    tags: ["role:controller", "spell:spell.suggestion", "condition:charmed", "shapechanger"],
    hookId: "hook.monster.spell",
  },
  {
    monsterId: "monster.lamia",
    abilityId: "intoxicating_touch",
    damage: { dice: "1d4", type: "psychic" },
    save: { ability: "wis", dcSource: "fixed", fixedDc: 13 },
    tags: ["role:controller", "attack:melee_weapon", "attack_bonus:+5", "condition:cursed", "spell_list:lamia"],
  },
  {
    monsterId: "monster.rakshasa",
    abilityId: "dominate_person",
    targeting: { type: "creature", rangeFt: 60 },
    save: { ability: "wis", dcSource: "fixed", fixedDc: 18 },
    tags: ["role:fiend_spellcaster", "spell:spell.dominate_person", "limited_magic_immunity", "social_infiltrator"],
    hookId: "hook.monster.spell",
  },
  {
    monsterId: "monster.mind_flayer",
    abilityId: "mind_blast",
    targeting: { type: "area", shape: "cone", sizeFt: 60 },
    save: { ability: "int", dcSource: "fixed", fixedDc: 15 },
    damage: { dice: "4d8+4", type: "psychic" },
    tags: ["role:psionic_controller", "condition:stunned", "recharge:5-6", "extract_brain"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.beholder",
    abilityId: "eye_rays",
    targeting: { type: "creature", rangeFt: 120 },
    save: { ability: "dex", dcSource: "fixed", fixedDc: 16 },
    damage: { dice: "10d8", type: "random_eye_ray" },
    tags: ["role:boss_controller", "random_ray:10", "condition:petrified", "condition:paralyzed", "legendary_like:lair_eye"],
    hookId: "hook.monster.save_condition",
  },
  {
    monsterId: "monster.beholder_zombie",
    abilityId: "eye_ray",
    targeting: { type: "creature", rangeFt: 60 },
    save: { ability: "con", dcSource: "fixed", fixedDc: 14 },
    damage: { dice: "10d8", type: "necrotic" },
    tags: ["role:undead_artillery", "random_ray:4", "condition:paralyzed", "condition:frightened"],
    hookId: "hook.monster.save_condition",
  },
  {
    monsterId: "monster.dragon_turtle",
    abilityId: "steam_breath",
    targeting: { type: "area", shape: "cone", sizeFt: 60 },
    save: { ability: "con", dcSource: "fixed", fixedDc: 18 },
    damage: { dice: "15d6", type: "fire" },
    tags: ["role:aquatic_boss", "recharge:5-6", "siege_monster", "amphibious"],
    hookId: "hook.monster.aoe_save",
  },
  {
    monsterId: "monster.merfolk_champion",
    abilityId: "spear",
    damage: { dice: "2d6+4", type: "piercing" },
    tags: ["role:aquatic_soldier", "attack:melee_weapon", "attack_bonus:+7", "leadership:reef_guard", "movement:swim:40"],
  },
  {
    monsterId: "monster.sea_hag",
    abilityId: "death_glare",
    targeting: { type: "creature", rangeFt: 30 },
    save: { ability: "wis", dcSource: "fixed", fixedDc: 11 },
    tags: ["role:aquatic_controller", "condition:frightened", "hp_threshold:drop_to_zero", "horrific_appearance"],
    hookId: "hook.monster.save_condition",
  },
  {
    monsterId: "monster.night_hag",
    abilityId: "nightmare_haunting",
    targeting: { type: "creature", rangeFt: null },
    damage: { dice: "1d10", type: "psychic" },
    tags: ["role:fiend_controller", "etherealness", "max_hp_reduction", "effect:campaign_downtime_threat"],
    hookId: "hook.monster.utility",
  },
  {
    monsterId: "monster.green_hag",
    abilityId: "illusory_appearance",
    targeting: SELF,
    tags: ["role:trickster", "illusion:disguise", "social_infiltration", "coven_spellcasting"],
    hookId: "hook.monster.utility",
  },
  {
    monsterId: "monster.tarrasque",
    abilityId: "frightful_presence",
    targeting: { type: "area", shape: "sphere", sizeFt: 120 },
    save: { ability: "wis", dcSource: "fixed", fixedDc: 17 },
    tags: ["role:mythic_boss", "condition:frightened", "legendary_like:resistance:3/day", "reflective_carapace", "phase:apex_predator"],
    hookId: "hook.monster.aoe_save",
  },
];

export const P5_MONSTER_ABILITY_DEFINITIONS: RuleCatalogEntry[] =
  P5_MONSTER_SEEDS.map(ability);
